module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    CATEGORY_COLLECTION:'Category',
    CART_COLLECTION:'cart',
    WISHLIST_COLLECTION:'wishlist',
    ORDER_COLLECTION:'order',
    BANNER_COLLECTION:'banner',
    COUPON_COLLECTION:'coupon',
    ADDRESS_COLLECTION:'ADDRESS',
}